### PR TITLE
clients/notifications: fix unclickable links in notifications list

### LINKED ISSUE #1603: Links in the notification menu don't open any page
For me the links in the bell / notifications menu don't open any page, looks like a `preventDefault()` something. The href of the anchors link to the GitHub issue page, but the link won't trigger when clicked on it. I couldn't find an issue about this so I can create one.

Screenshot of the links in question

*This is a screenshot of the links in question*

### PR DESCRIPTION
**Pull request by emilwidlund**
Fixes #1603.

### CODE REVIEW

File: clients/apps/web/src/components/Notifications/Popover.tsx [hunk 1]
```diff
@@ -112,10 +112,6 @@ const Popover = ({ type = 'topbar' }: { type?: 'topbar' | 'dashboard' }) => {
           aria-live="assertive"
           className={notificationsContainerClassnames}
           ref={ref}
-          onClick={(e) => {
-            e.preventDefault()
-            e.stopPropagation()
-          }}
```
Comment (zegl) [inline clients/apps/web/src/components/Notifications/Popover.tsx:118]: I wonder why this was here 😕

Comment (emilwidlund) [reply clients/apps/web/src/components/Notifications/Popover.tsx:118]: Me neither. I suspect it was needed when we had the notification area in the topbar; but that doesn't really make sense neither.
