### PR TITLE
fix(web): resolved glitches while removing social url

### LINKED ISSUE #6728: Can't completely remove social media URL in profile settings
### Description

When adding a social media link in profile settings, you can't fully delete it — the first letter of the URL stays even after clearing the input.

### Current Behavior

The first letter of the URL can't be removed.

### Expected Behavior

Users should be able to completely clear the URL field and rewrite it if they make a mistake.

### Screenshots

https://github.com/user-attachments/assets/6ecc9987-897c-437a-ab06-6d2d03392b1b

### PR DESCRIPTION
**Pull request by rajdip-b**
## Description

Fixes #6728

Social URLs can now be cleared completely by hitting backspace. Here's a demo:

https://github.com/user-attachments/assets/0676fba5-1a78-4118-a52e-bcede9375c3f

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -137,3 +137,5 @@ playground.py
 server/tests/invoice/test_invoice*.pdf
 supervisord.pid
 server/.minio/
+
+.idea/
```
Comment (frankie567) [inline .gitignore]: Remove the change to .gitignore

File: clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx [hunk 2]
```diff
@@ -117,28 +117,24 @@ const OrganizationSocialLinks = () => {
...
   const handleChange = (index: number, value: string) => {
-    if (!value) return
-
-    // Add protocol if missing
-    if (!value.startsWith('https://')) {
-      value = 'https://' + value
-    } else if (value.startsWith('http://')) {
-      value = value.replace('http://', 'https://')
+    const currentFieldValue = socials[index]?.url
+    console.log('currentFieldValue', currentFieldValue)
```
Comment (frankie567) [inline clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx]: Remove console.log

File: clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx [hunk 3]
```diff
@@ -117,28 +117,24 @@ const OrganizationSocialLinks = () => {
...
+    if (currentFieldValue === '') {
+      value = 'https://'+value
     }
 
-    try {
-      const url = new URL(value)
+    // Infer the platform from the URL
+    let newPlatform: schemas['OrganizationSocialPlatforms'] = 'other'
+    try { const url = new URL(value)
```
Comment (frankie567) [inline clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx]: Can we format the the code? It doesn't look great like this. For the record, we have a prettier configuration available in the repo.

**Review by frankie567 — CHANGES_REQUESTED** [review]
Thank you for tackling this! A few tweaks and this should be good to go 👍

File: .gitignore (hunk 1 above)
Comment (rajdip-b) [reply .gitignore]: This adds my IDE stuff into the repository. Would that be a good idea?

File: clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx (hunk 2 above)
Comment (rajdip-b) [reply clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx]: Ah dang! sure I will

File: clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx (hunk 3 above)
Comment (rajdip-b) [reply clients/apps/web/src/components/Settings/OrganizationProfileSettings.tsx]: yeah sure. oversight on my end.

**Comment by rajdip-b** [comment]
Applied the changes! Should be good now :D

**Comment by rajdip-b** [comment]
Hey @frankie567! Do you think this is good to merge?

**Comment by frankie567** [comment]
Yes, thank you 👍

**Review by frankie567 — APPROVED** [review]
